input_file: 'result/feature/test/fea_morganfp.csv'
output_path: 'model/pre_model/PROTAC/'
seed: 42

model:
    type: "TabPFN" #TabPFN, LightGBM, AutoGluon
    tabpfn:
        device: 'cuda' #cuda or cpu
        ignore_pretraining_limits: False
    lightgbm:
        param_tune: True
        n_jobs: -1
